version: 2

defaults: &defaults
  executors:
    machine_executor_amd64:
      machine:
        image: ubuntu-2204:2022.04.2
      environment:
        architecture: "amd64"
        platform: "linux/amd64"
  steps:
    - setup_remote_docker:
        version: 20.10.14
        docker_layer_caching: true
    - checkout
    - run: .circleci/build.sh
    - run:
        command: docker-compose run --rm test-rest
        working_directory: test
        when: always
    - run:
        command: docker-compose run --rm test-graphql
        working_directory: test
        when: always
    - run:
        command: docker-compose run --rm test-acceptance.webdriverio
        working_directory: test
        when: always
    - run:
        command: docker-compose run --rm test-acceptance.puppeteer
        working_directory: test
        when: always
    - run:
        command: docker-compose run --rm test-bdd.faker
        working_directory: test
        when: always

jobs:
  docker:
    <<: *defaults
    environment:
      - NODE_VERSION: 12.8.0

workflows:
  version: 2

  test_all:
    jobs:
      - docker
